version: '3.8'

services:
  chen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ip2
    privileged: true
    user: "1004:1004"
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
      - PATH=/app/pgsql/bin:${PATH}
    volumes:
     - type: bind
       source: /Users/songchen/Documents/project/ip2
       target: /app
    working_dir: /app
    stdin_open: true  # 保持标准输入打开
    tty: true         # 启用伪终端